name: Step3 Code Review

on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

jobs:
  claude-review:
    if: |
      (github.event_name == 'pull_request' && (
        contains(github.event.pull_request.title, 'step3') ||
        contains(github.event.pull_request.title, 'Step3') ||
        contains(github.event.pull_request.title, '3단계') ||
        contains(github.event.pull_request.labels.*.name, 'step3')
      )) ||
      (github.event_name == 'issue_comment' && 
       github.event.issue.pull_request && 
       contains(github.event.comment.body, '@claude review'))

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ap-northeast-2

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          use_bedrock: true
          timeout_minutes: '30'
          model: 'apac.anthropic.claude-sonnet-4-20250514-v1:0'

          # Direct prompt for automated review (no @claude mention needed)
          direct_prompt: |
            ## 🎯 Step 3 트랜잭션 구현 미션 달성도 중심 리뷰 가이드라인
            
            **이 리뷰는 Step 3 트랜잭션 구현 미션 요구사항 달성에 집중합니다.**
            비밀번호 변경과 이력 저장의 원자성을 보장하는 트랜잭션 기능 구현을 중점적으로 검토하고 **한글로** 피드백을 제공해주세요.
            
            ### 📚 학습 원칙
            - **직접 코드를 제공하지 마세요** (학습자가 명시적으로 요청하는 경우 제외)
            - **문제 해결 과정을 안내**하되, 정답을 바로 알려주지 마세요
            - **작은 단계로 문제를 분해**하여 접근하도록 도와주세요
            
            ### 💡 피드백 방법
            - **유도 질문 활용**: "만약 ~라면 어떻게 될까요?", "~를 고려해보셨나요?"
            - **힌트 제공**: 방향은 제시하되, 구체적인 구현은 학습자가 하도록
            - **다양한 접근법 제시**: 한 가지 해결책이 아닌 여러 가능성을 제안
            - **왜?에 집중**: 단순히 무엇이 잘못되었는지보다 왜 그런지 이해하도록
            
            ### 🔍 디버깅 독립성 강화
            - 에러 메시지를 **스스로 읽고 이해**하도록 격려
            - 로그 활용법 안내 (System.out.println, logger, 디버거 활용)
            - 문제 패턴 파악을 도와 **디버깅 스킬 향상**
            - 관련 문서나 JavaDoc 참조 권장
            
            ### 📋 미션 달성도 체크리스트
            
            #### 1. 트랜잭션 경계 설정
            - [ ] Connection.setAutoCommit(false)를 통한 트랜잭션 시작
            - [ ] 비즈니스 로직 성공 시 commit() 호출
            - [ ] 예외 발생 시 rollback() 호출로 원자성 보장
            
            #### 2. Connection 객체 공유
            - [ ] UserDao와 UserHistoryDao가 동일한 Connection 사용
            - [ ] DAO 메서드에 Connection 매개변수 추가
            - [ ] changePassword() 메서드에서 Connection 전달
            
            #### 3. UserServiceTest 통과
            - [ ] @Disabled 어노테이션 제거 후 모든 테스트 통과
            - [ ] 트랜잭션 롤백 시나리오 검증
            - [ ] 정상 커밋 시나리오 검증
            
            ### 🎓 핵심 학습 포인트
            - **트랜잭션 개념**: ACID 속성과 원자성 보장의 중요성 이해
            - **Connection 관리**: 동일한 Connection 객체 공유를 통한 트랜잭션 경계 설정
            - **예외 처리**: 트랜잭션 롤백을 위한 적절한 예외 처리 구조
            - **리소스 관리**: try-with-resources를 활용한 Connection 자동 해제
            - **데이터 일관성**: 중간 실패 시 원래 상태로의 복원 보장
            
            ### 🌟 학습 완료 후
            - "이번 구현을 통해 무엇을 배우셨나요?" 같은 **회고 질문**
            - 비슷한 문제를 만났을 때 적용 가능한 **패턴 인식**
            - 다음 단계 학습을 위한 **추가 학습 자료** 제안
            
            ### ⚠️ 예외 상황
            - 학습자가 "코드를 보여주세요" 등 **명시적으로 요청**시에만 코드 제공
            - 개념 설명 요청시 (예: "서블릿이 뭔가요?") **명확하고 직접적인 설명** 제공
            
            **리뷰는 건설적이고 격려하는 톤으로 작성하며, 학습자의 성장을 최우선으로 고려해주세요.**
